spring.application.name=app
#Without this, Spring won't auto-create your PostgreSQL tables:
spring.jpa.hibernate.ddl-auto=update
#postgreSql
spring.datasource.url=jdbc:postgresql://localhost:5432/chat_app_users_db
spring.datasource.username=postgres
spring.datasource.password=12345
#mongoDB
spring.mongodb.uri=mongodb://localhost:27017/chat_db

# one secret for the whole server
jwt.secret=thisIsMySecretKeyForSigningTokens123!
# 24 hours in milliseconds
jwt.expiration=86400000


logging.level.org.springframework.security=DEBUG
